# Custom Language File for Launcher Customizer

[ejs.app]
title = "지앤빌리지"

[ejs.landing]
mediaGitHubURL = "https://github.com/mchlauncher/JiAnd-Village"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/vKksMy3H"
mediaSoopURL = "https://ch.sooplive.co.kr/jiand0502"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/mchlauncher/JiAnd-Village"
supportLink = "https://github.com/mchlauncher/JiAnd-Village/issues"

[ejs.welcome]
welcomeHeader = "지앤빌리지"
welcomeDescription = ""
welcomeDescCTA = "[계속] 버튼을 눌러 계속 진행하여 주세요."